### PR TITLE
Update pprof

### PR DESCRIPTION
**Pull request by cristaloleg**
Looks like the previous version is from June 2020, time for the update ;)

### CODE REVIEW

**Comment by felixge** [comment]
Sure, why not : ). Thanks!

**Comment by cristaloleg** [comment]
Nice, can you tag a release, please?

**Comment by felixge** [comment]
Yes ... but before I do this, is there any particular reason you're so eager to get this upgraded in fgprof? Arguably you could also do it from your own go.mod file?

**Comment by cristaloleg** [comment]
Well...not really. Just have found that there were many fixes in google/pprof, so good to be on track for everyone too.

Why I'm interested in fgprof at all? - making a small repo to have easiest way to enable all possible profilers https://github.com/go-perf/easypprof BTW thanks for fgprof ;)

**Comment by felixge** [comment]
Alright, sounds good. https://github.com/felixge/fgprof/releases/tag/v0.9.2 here you go : ). Good luck with your project.

**Pull request merged**
