### PR TITLE
Default to 30s duration like net/http/pprof

### PR DESCRIPTION
**Pull request by felixge**
GH-Issue: https://github.com/felixge/fgprof/issues/3

### CODE REVIEW

**Comment by cristaloleg** [comment]
Probably `timeout` will be better (same as pprof), wdyt?

**Comment by felixge** [comment]
@cristaloleg afaik Go also calls this argument `seconds`, not `timeout`? See https://golang.org/src/net/http/pprof/pprof.go?s=3563:3615#L109

**Comment by cristaloleg** [comment]
Yep, you're right! Was looking at #3 with `?timeout` in text :(

**Comment by chonlasit907** [comment]
https://golang.org/src/net/http/pprof/pprof.go?s=3563:3615#L109

**Comment by felixge** [comment]
> Yep, you're right! Was looking at #3 with ?timeout in text :(

No worries, I got confused by that as well, but I assume @howardjohn meant `seconds` as well.

**Comment by howardjohn** [comment]
Yep I meant seconds, sorry for the confusion!

**Pull request merged**
